### ISSUE TITLE
Valid Padded Behavior

### ISSUE THREAD

**Issue by mgriffin1994** [SHI-Labs/Neighborhood-Attention-Transformer#14]
First off, great paper! I've been looking for transformers with some of the same locality inductive biases as CNNs. I was wondering if you would be able to add support for a valid padding based alternative though. So rather than handling the edges with the altered behavior, just allow reduced output size like in valid padded convolution layers. This is very important in the domain we work in where we need to be equivariant to the specific crop of the image and the dimensions of the input at inference time.

**Comment by PeiqinZhuang** [comment]
> First off, great paper! I've been looking for transformers with some of the same locality inductive biases as CNNs. I was wondering if you would be able to add support for a valid padding based alternative though. So rather than handling the edges with the altered behavior, just allow reduced output size like in valid padded convolution layers. This is very important in the domain we work in where we need to be equivariant to the specific crop of the image and the dimensions of the input at inference time.

I agree with the solution. It is more natural to remain the geometric relationship within that window even if the anchor pixel is at the edge of the image. It is easy to apply padding and unfold operations in PyTorch.  I am also curious about this natural solution compared with the altered solution.

**Comment by PeiqinZhuang** [comment]
I agree with this point. It is more natural to apply padding operation in order to remain the geometric relationship within that window even if the query pixel is at the edge. It is easy to perform padding and unfold operations in Pytorch. I am also curious about this padding solution compared with the altered solution.

**Comment by alihassanijr** [comment]
Hello and thank you for your interest,
I believe it is possible to be done within the kernel, and it is on our to-do list of creating a general torch extension (with support for different paddings, strides, and dilation). 
But for now, you can alternatively just mask or crop the outputs to get the valid padding behavior.
For that you can just take the output of `NeighborhoodAttention`, which is `B x H x W x C`, similar to the input, and crop out the expected region. It would look something like this:
```python3
B, H, W, C = x.shape
x = neighborhoodattn(x)
pad = kernel_size // 2
Hn, Wn = H - 2*pad, W - 2*pad
x = x[:, pad:pad+Hn, pad:pad+Wn, :]

B1, H1, W1, C1 = x.shape
assert H1 == Hn and W1 == Wn
```

I hope this helps. If you have any questions as to why this would be equivalent to a valid pad, please let me know.

**Comment by alihassanijr** [comment]
I'm closing this issue now because we're moving our extension to its own [separate repository](https://github.com/SHI-Labs/NATTEN), and due to inactivity.

We do not currently have plans for supporting valid padding natively in our kernel.

Please feel free to reopen it if you still have questions, or open an issue in [NATTEN](https://github.com/SHI-Labs/NATTEN) if it's related to that.
